### ISSUE TITLE
a few suggestions 

### ISSUE THREAD

**Issue by KeLaiFu** [arthursaunier/Synth#1]
The drumbox module looks a lot of fun, I was just wondering how difficult it would be to add a couple of things. Firstly, a manual trigger button for each sound and more useful, a single output with all 4 channels combined.

Looking at building a bunch of your modules anyway, so thanks for sharing

**Comment by arthursaunier** [comment]
Hello! 

It's not difficult at all! I actually started working on your ideas today. I'll try to finish it in a couple of days! 
Glad you like them, and thanks for your suggestions!

**Comment by KeLaiFu** [comment]
> It's not difficult at all! I actually started working on your ideas today. I'll try to finish it in a couple of days! Glad you like them, and thanks for your suggestions!

well that's awesome news, I was just scratching my head on how to do the triggers myself, but I wasn't getting very far! really appreciate you sharing the kicad files too.

**Comment by arthursaunier** [comment]
Hey, Just so you know, I've updated the kicad files and the gerber. Your recommendations are in V1.1 of the drumbox folder.

**Comment by arthursaunier** [comment]
Oh, and almost forgot, would love to have pictures if you end up buillding any of the modules! Cheers

**Comment by KeLaiFu** [comment]
I was just talking about this with someone else earlier today and coincidentally you added the update at pretty much the same time. I will add this to my next jlc order in a few weeks, although I do plan to make it a bit more compact first. Thanks again for your hard work, and also for sharing the kicad files.

**Comment by KeLaiFu** [comment]
another quick question, the decay pots are marked as 470k, which I looked for and only found panel mount style ones. Would a 500k one do the job?

**Comment by arthursaunier** [comment]
A 500k pot would definitly do the job!
