### ISSUE TITLE
drumbox C7 and C8 are decoupling for the opamp?

### ISSUE THREAD

**Issue by KeLaiFu** [arthursaunier/Synth#10]
I've had some time to work on my version of your drumbox and I have almost finished. I noticed that there's a couple of 100nF electrolytic caps in the schematic that dont seem to have a specific location. Are these the decoupling caps for the opamp?

**Comment by arthursaunier** [comment]
Hey, 
Yep they are just decoupling caps, you can replace them by non electrolytic caps, using ceramics would be fine, it's actually what I should have done :)
I'm currently going over all my designs and updating them and correcting stuff. As of yet, I haven't done this one.

**Comment by KeLaiFu** [comment]
> Hey, Yep they are just decoupling caps, you can replace them by non electrolytic caps, using ceramics would be fine, it's actually what I should have done :) I'm currently going over all my designs and updating them and correcting stuff. As of yet, I haven't done this one.

I have squeezed your drumbox onto a single 12HP PCB, although I have worked on it sporadically with large gaps between kicad sessions, so I am fully expecting I have broken it. The PCB is pretty much done, so I will send it off to jlc soon and all being well I can upload it to my github when (if) it works. Changing those 2 caps to ceramics will help, so thanks!
