### ISSUE TITLE
drumbox pots backwards?

### ISSUE THREAD

**Issue by KeLaiFu** [arthursaunier/Synth#11]
been saying this for months, but...almost ready to send the drumbox to jlc for fabrication and I noticed that if I switch out the footprint for the pitch pots, the replacement pots have the wiring effectively flipped. I won't pretend to understand why this is happening, but I would guess that the pots on the original have the usual error where they work in reverse.
So, should I change the wiring or am i fixing a problem that doesn't exist?

**Comment by arthursaunier** [comment]
Yep, on the first versions the pots were backward, so that would explain this issue.
