### ISSUE TITLE
Panel-size / PCB-postion StupidBox

### ISSUE THREAD

**Issue by CoogLFish** [arthursaunier/Synth#9]
I ordered the PCBs at JLCPCB and the panel came out several millimeters too long, which deems it unusable in a standard eurorack. The position of the main PCB is off as well, there is no space left on the bottom to screw it in the rack. Not sure if it's a production error or the gerbers are in the wrong format.

**Comment by arthursaunier** [comment]
Hey, 
I'm really sorry, this build was one of my first designs and I did it all wrong.... :/ It is functional, but effectively, the panel and the PCB are not the right size at all.

I changed the status of this repo, all my future designs (with up to dates files and Gerber) will be updated on an organization called Bleepsound. You can find the link on the repo.
